# zsh-bw-keys — lazy Bitwarden secret injection for shell env vars
# Usage:
#   bw-key-register VAR_NAME bw-item-name [trigger-commands...]
#   Example: bw-key-register GITHUB_TOKEN github-pat npm pnpm bun yarn
#   bw-keys-clear   # clear the cached session + loaded keys (forces re-unlock)
#
# Options (set anywhere in your zshrc, before or after sourcing):
#   export BW_KEYS_BIOMETRIC=1   # unlock via biometrics (bwbio) — default off

typeset -gA _BW_KEY_ITEMS    # VAR_NAME -> Bitwarden item name
typeset -gA _BW_KEY_TRIGGERS # VAR_NAME -> space-separated trigger commands
typeset -g _BW_KEYS_SESSION_FILE="/tmp/.bw_session"
typeset -g _BW_KEYS_LAST_LINE=""
typeset -g _BW_KEYS_PLUGIN_FILE="${${(%):-%N}:A}"
typeset -g _BW_KEYS_SHIM_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh-bw-keys/bin"
typeset -g _BW_KEYS_SHIM_STATE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh-bw-keys/loaded"
typeset -gA _BW_KEYS_COLORS=(green '1;32' red '1;31' yellow '1;33' dim '2')

# Print a status line to stderr in the given color (green|red|yellow|dim).
_bw_keys_msg() {
  local color="$1"
  shift
  echo -e "\e[${_BW_KEYS_COLORS[$color]}m$*\e[0m" >&2
}

# Pure lookup: set $reply to the var names whose trigger list contains any
# of the given words.
_bw_keys_vars_for_cmds() {
  reply=()
  local var_name
  for var_name in ${(k)_BW_KEY_ITEMS}; do
    local triggers=(${(z)_BW_KEY_TRIGGERS[$var_name]})
    local hits=("${(@)triggers:*argv}")
    (( ${#hits} )) && reply+=("$var_name")
  done
}

# Keep the shim dir first in PATH so shims win over the real binaries —
# even when something later in zshrc (volta, nvm, ...) prepends its own dirs.
_bw_keys_ensure_shim_path() {
  [[ "${path[1]:-}" == "$_BW_KEYS_SHIM_DIR" ]] && return 0
  path=("$_BW_KEYS_SHIM_DIR" "${(@)path:#$_BW_KEYS_SHIM_DIR}")
}

bw-key-register() {
  if [[ $# -lt 2 ]]; then
    echo "usage: bw-key-register VAR_NAME bw-item-name [trigger-commands...]" >&2
    return 1
  fi
  local var_name="$1"
  local bw_item="$2"
  shift 2
  _BW_KEY_ITEMS[$var_name]="$bw_item"
  _BW_KEY_TRIGGERS[$var_name]="${*}"

  # Wrap each trigger command in a function so the key is loaded (prompting
  # for unlock if needed) right before the command runs — even in compound
  # commands like `foo && npm i`. If loading fails the command is aborted
  # instead of crashing on the missing env var.
  local cmd
  for cmd in "$@"; do
    eval "${cmd}() { _bw_keys_run_trigger ${(q)cmd} \"\$@\" }"
    _bw_keys_write_shim "$cmd"
  done
  if (( $# )); then
    _bw_keys_ensure_shim_path
  fi
}

# Write a PATH shim for a trigger command. The function wrapper above is
# bypassed by `command npm`, scripts, and other shells — a real executable
# first in PATH catches all of those. The shim sources this plugin with the
# registry reduced to the relevant vars, then hands off to _bw_keys_shim_main.
_bw_keys_write_shim() {
  local cmd="$1"
  _bw_keys_vars_for_cmds "$cmd"
  local var_name pairs=""
  for var_name in $reply; do
    pairs+=" ${(qq)var_name} ${(qq)_BW_KEY_ITEMS[$var_name]}"
  done
  [[ -n "$pairs" ]] || return 0

  mkdir -p "$_BW_KEYS_SHIM_DIR"
  cat > "$_BW_KEYS_SHIM_DIR/$cmd" <<EOF
#!/usr/bin/env zsh
# generated by zsh-bw-keys — do not edit
source ${(qq)_BW_KEYS_PLUGIN_FILE}
_BW_KEY_ITEMS=($pairs )
_bw_keys_shim_main ${(qq)cmd} "\$@"
EOF
  chmod +x "$_BW_KEYS_SHIM_DIR/$cmd"
}

# Entry point for generated shims: drop the shim dir from PATH, load every
# missing key (recording it for the parent shell to pick up), then exec the
# real command.
_bw_keys_shim_main() {
  local cmd="$1"
  shift
  path=("${(@)path:#$_BW_KEYS_SHIM_DIR}")
  local var_name
  for var_name in ${(k)_BW_KEY_ITEMS}; do
    [[ -n "${(P)var_name:-}" ]] && continue
    _bw_keys_load_var "$var_name" || {
      _bw_keys_msg yellow "↻ ${var_name} not loaded — aborted '${cmd}'."
      exit 1
    }
    print -r -- "$var_name" >> "$_BW_KEYS_SHIM_STATE"
  done
  exec "$cmd" "$@"
}

# Clear the cached session and all loaded keys — forces a fresh unlock and
# reload on the next trigger.
bw-keys-clear() {
  unset BW_SESSION
  rm -f "$_BW_KEYS_SESSION_FILE" "$_BW_KEYS_SHIM_STATE"
  local var_name
  for var_name in ${(k)_BW_KEY_ITEMS}; do
    if [[ -n "${(P)var_name:-}" ]]; then
      unset "$var_name"
      _bw_keys_msg green "✓ ${var_name} cleared"
    else
      _bw_keys_msg dim "- ${var_name} was not set"
    fi
  done
  _bw_keys_msg green "✓ Bitwarden session cache cleared"
}

_bw_keys_ensure_session() {
  command -v bw >/dev/null || {
    _bw_keys_msg red "✗ Bitwarden CLI not installed (brew install bitwarden-cli)"
    return 1
  }

  if [[ -z "${BW_SESSION:-}" && -f "$_BW_KEYS_SESSION_FILE" ]]; then
    BW_SESSION="$(cat "$_BW_KEYS_SESSION_FILE")"
    export BW_SESSION
  fi

  # Validate the session — it goes stale after `bw lock`, logout, etc.
  if [[ -n "${BW_SESSION:-}" ]]; then
    bw unlock --check --session "$BW_SESSION" >/dev/null 2>&1 && return 0
    _bw_keys_msg yellow "⚠ Cached Bitwarden session is stale — re-unlocking..."
    unset BW_SESSION
    rm -f "$_BW_KEYS_SESSION_FILE"
  else
    _bw_keys_msg yellow "🔒 Bitwarden vault locked — unlocking..."
  fi

  # Opt-in biometric unlock via bwbio (github.com/jeanregisser/bitwarden-cli-bio):
  # asks the Bitwarden desktop app for Touch ID / Windows Hello and falls back
  # to a password prompt by itself. Off by default — set BW_KEYS_BIOMETRIC=1.
  if [[ "${BW_KEYS_BIOMETRIC:-0}" == "1" ]] && command -v bwbio >/dev/null; then
    BW_SESSION="$(bwbio unlock --raw)" || return 1
  else
    BW_SESSION="$(bw unlock --raw)" || return 1
  fi
  export BW_SESSION
  (umask 077; echo "$BW_SESSION" > "$_BW_KEYS_SESSION_FILE")
}

# Load one registered key into its env var (no-op if already set).
_bw_keys_load_var() {
  local var_name="$1"
  [[ -n "${(P)var_name:-}" ]] && return 0

  _bw_keys_ensure_session || return 1

  local val
  val="$(bw get password "${_BW_KEY_ITEMS[$var_name]}" --session "$BW_SESSION" 2>/dev/null)" || {
    _bw_keys_msg red "✗ Failed to load ${var_name} from Bitwarden item '${_BW_KEY_ITEMS[$var_name]}'"
    return 1
  }

  [[ -z "$val" ]] && {
    _bw_keys_msg red "✗ ${var_name}: Bitwarden item '${_BW_KEY_ITEMS[$var_name]}' returned empty"
    return 1
  }

  export "${var_name}=${val}"
  _bw_keys_msg green "✓ ${var_name} loaded"
}

# Load every key registered without trigger commands.
_bw_keys_load_untriggered() {
  local var_name
  for var_name in ${(k)_BW_KEY_ITEMS}; do
    [[ -n "${_BW_KEY_TRIGGERS[$var_name]}" ]] && continue
    _bw_keys_load_var "$var_name"
  done
}

# Wrapper entry point: load every key triggered by this command, then run
# the real command. Aborts if a key cannot be loaded.
_bw_keys_run_trigger() {
  local cmd="$1"
  shift
  _bw_keys_vars_for_cmds "$cmd"
  local var_name vars=($reply)
  for var_name in $vars; do
    _bw_keys_load_var "$var_name" || {
      _bw_keys_msg yellow "↻ ${var_name} not loaded — aborted '${cmd}'. Run your command again."
      return 1
    }
  done
  command "$cmd" "$@"
}

# Pick up keys a shim loaded for a child process, so the parent shell has
# them too and the next run skips the Bitwarden round-trip entirely.
_bw_keys_pickup_shim_state() {
  [[ -s "$_BW_KEYS_SHIM_STATE" ]] || return 0
  local v
  while IFS= read -r v; do
    [[ -n "${_BW_KEY_ITEMS[$v]:-}" ]] && _bw_keys_load_var "$v"
  done < "$_BW_KEYS_SHIM_STATE"
  rm -f "$_BW_KEYS_SHIM_STATE"
}

# Before each command: remember the line (for post-run recovery) and load
# keys registered without triggers.
_bw_keys_preexec() {
  _BW_KEYS_LAST_LINE="$1"
  _bw_keys_load_untriggered
}

# After each command: if a trigger word appeared anywhere in the line but its
# key is still missing (cancelled unlock, wrapper bypassed, stale session),
# prompt to unlock now and tell the user to re-run the command.
_bw_keys_precmd() {
  _bw_keys_ensure_shim_path
  _bw_keys_pickup_shim_state

  local line="$_BW_KEYS_LAST_LINE"
  _BW_KEYS_LAST_LINE=""
  [[ -n "$line" ]] || return 0

  _bw_keys_vars_for_cmds ${(z)line}
  local var_name missing=()
  for var_name in $reply; do
    [[ -z "${(P)var_name:-}" ]] && missing+=("$var_name")
  done
  (( ${#missing} )) || return 0

  _bw_keys_msg yellow "⚠ Command needed ${(j:, :)missing} but it was not loaded — unlocking now..."
  local ok=1
  for var_name in $missing; do
    _bw_keys_load_var "$var_name" || ok=0
  done
  (( ok )) && _bw_keys_msg green "↻ Keys loaded — run your command again."
}

# Hooks are only useful in interactive shells — and in scripts (like the
# generated shims) the preexec hook would eagerly load every trigger-less key.
if [[ -o interactive ]]; then
  autoload -Uz add-zsh-hook
  add-zsh-hook preexec _bw_keys_preexec
  add-zsh-hook precmd _bw_keys_precmd
fi
